/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ui;

import com.dao.truyenDAO;
import com.models.Truyen;
import com.utils.Auth;
import com.utils.MsgBox;
import com.utils.Renderer;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;

/**
 *
 * @author admin
 */
public class mainForm extends javax.swing.JFrame {

    /**
     * Creates new form mainForm
     */
    truyenDAO tRDAO = new truyenDAO();
    public static String name = "";

    public mainForm() {
        initComponents();
        mnu.setVisible(false);
        fill();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Desktop1 = new javax.swing.JDesktopPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        btnRank = new javax.swing.JButton();
        btnSearch = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        btnHistory = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jPanel4 = new javax.swing.JPanel();
        btnHome = new javax.swing.JButton();
        btnFolow = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        btnCate = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JSeparator();
        btnACC = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        mnu = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuDX = new javax.swing.JMenuItem();
        menuDMK = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menuTruyen = new javax.swing.JMenuItem();
        menuChuong = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        menuTG = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        menuTL = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnRank.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnRank.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/image/rank.png"))); // NOI18N
        btnRank.setText("Xếp hạng");
        btnRank.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnRank.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnRank.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRankActionPerformed(evt);
            }
        });

        btnSearch.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/image/search.png"))); // NOI18N
        btnSearch.setText("Tìm kiếm");
        btnSearch.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSearch.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        btnHistory.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnHistory.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/image/clock.png"))); // NOI18N
        btnHistory.setText("Lịch sử");
        btnHistory.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnHistory.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHistoryActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(btnRank, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(12, 12, 12)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnHistory, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jSeparator1)
            .addComponent(btnRank, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
            .addComponent(jSeparator2)
            .addComponent(btnHistory, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jList1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jList1.setModel(new DefaultListModel());
        jList1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 567, Short.MAX_VALUE)
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnHome.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/image/house.png"))); // NOI18N
        btnHome.setText("Home");
        btnHome.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnHome.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });

        btnFolow.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnFolow.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/image/heart.png"))); // NOI18N
        btnFolow.setText("Theo dõi");
        btnFolow.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnFolow.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnFolow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFolowActionPerformed(evt);
            }
        });

        jSeparator3.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jSeparator4.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);

        btnCate.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnCate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/image/scroll-bar.png"))); // NOI18N
        btnCate.setText("Thể loại");
        btnCate.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCate.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jSeparator5.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator5.setOrientation(javax.swing.SwingConstants.VERTICAL);

        btnACC.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnACC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/image/user.png"))); // NOI18N
        btnACC.setText("Tài khoản");
        btnACC.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnACC.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnACC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnACCActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(btnHome, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnFolow, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCate, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnACC, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator3)
            .addComponent(jSeparator4)
            .addComponent(jSeparator5)
            .addComponent(btnFolow, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btnHome, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btnCate, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btnACC, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Truyện mới cập nhật");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(20, 20, 20)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        Desktop1.setLayer(jPanel2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout Desktop1Layout = new javax.swing.GroupLayout(Desktop1);
        Desktop1.setLayout(Desktop1Layout);
        Desktop1Layout.setHorizontalGroup(
            Desktop1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        Desktop1Layout.setVerticalGroup(
            Desktop1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        mnu.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        mnu.setPreferredSize(new java.awt.Dimension(126, 32));

        jMenu1.setText("Hệ thống");
        jMenu1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        menuDX.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        menuDX.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/image/Stop.png"))); // NOI18N
        menuDX.setText("Đăng xuất");
        menuDX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuDXActionPerformed(evt);
            }
        });
        jMenu1.add(menuDX);

        menuDMK.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        menuDMK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/image/Refresh.png"))); // NOI18N
        menuDMK.setText("Đổi mật khẩu");
        menuDMK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuDMKActionPerformed(evt);
            }
        });
        jMenu1.add(menuDMK);

        mnu.add(jMenu1);

        jMenu2.setText("Truyện");
        jMenu2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenu2.setPreferredSize(new java.awt.Dimension(65, 24));

        menuTruyen.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        menuTruyen.setText("Quản lý truyện");
        menuTruyen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuTruyenActionPerformed(evt);
            }
        });
        jMenu2.add(menuTruyen);

        menuChuong.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        menuChuong.setText("Quản lý chương");
        menuChuong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuChuongActionPerformed(evt);
            }
        });
        jMenu2.add(menuChuong);

        mnu.add(jMenu2);

        jMenu3.setText("Tác giả");
        jMenu3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        menuTG.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        menuTG.setText("Quản lý tác giả");
        menuTG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuTGActionPerformed(evt);
            }
        });
        jMenu3.add(menuTG);

        mnu.add(jMenu3);

        jMenu4.setText("Thể loại");
        jMenu4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        menuTL.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        menuTL.setText("Quản lý thể loại");
        menuTL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuTLActionPerformed(evt);
            }
        });
        jMenu4.add(menuTL);

        mnu.add(jMenu4);

        setJMenuBar(mnu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Desktop1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Desktop1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRankActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRankActionPerformed

    }//GEN-LAST:event_btnRankActionPerformed

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHomeActionPerformed

    private void menuDXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuDXActionPerformed
        // TODO add your handling code here:
        if (Auth.isManager()) {
            mnu.setVisible(false);
        }
        Auth.clear();
    }//GEN-LAST:event_menuDXActionPerformed

    private void menuDMKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuDMKActionPerformed
        // TODO add your handling code here:
        DoiMatKhau dmk = new DoiMatKhau();
        Desktop1.add(dmk);
        dmk.setVisible(true);
    }//GEN-LAST:event_menuDMKActionPerformed

    private void menuTruyenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuTruyenActionPerformed
        // TODO add your handling code here:
        QuanLyTruyen truyen = new QuanLyTruyen();
        Desktop1.add(truyen);
        truyen.setVisible(true);
    }//GEN-LAST:event_menuTruyenActionPerformed

    private void menuChuongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuChuongActionPerformed
        // TODO add your handling code here:
        QuanLyChuong chuong = new QuanLyChuong();
        Desktop1.add(chuong);
        chuong.setVisible(true);
    }//GEN-LAST:event_menuChuongActionPerformed

    private void menuTGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuTGActionPerformed
        // TODO add your handling code here:
        QuanLyTacGia tG = new QuanLyTacGia();
        Desktop1.add(tG);
        tG.setVisible(true);
    }//GEN-LAST:event_menuTGActionPerformed

    private void menuTLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuTLActionPerformed
        // TODO add your handling code here:
        QuanLyTheLoai tLoai = new QuanLyTheLoai();
        Desktop1.add(tLoai);
        tLoai.setVisible(true);
    }//GEN-LAST:event_menuTLActionPerformed

    private void jList1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList1MouseClicked
        // TODO add your handling code here:
        Object sel = null;

        int[] selectedIx = this.jList1.getSelectedIndices();

        for (int i = 0; i < selectedIx.length; i++) {
            sel = jList1.getModel().getElementAt(selectedIx[i]);
        }
        name = String.valueOf(sel);
        System.out.println(sel);
        ThongTinTruyen ttr = new ThongTinTruyen();

        Desktop1.add(ttr);
        ttr.setVisible(true);
    }//GEN-LAST:event_jList1MouseClicked

    private void btnACCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnACCActionPerformed
        // TODO add your handling code here:
        Login lg = new Login();
        Desktop1.add(lg);
        lg.setVisible(true);
    }//GEN-LAST:event_btnACCActionPerformed

    private void btnFolowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFolowActionPerformed
        // TODO add your handling code here:
        if (Auth.user == null) {
            MsgBox.alert(this, "Bạn cần đăng nhập để thực hiện chức năng");
        }
    }//GEN-LAST:event_btnFolowActionPerformed

    private void btnHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHistoryActionPerformed
        // TODO add your handling code here:
        LichSu ls = new LichSu();
        Desktop1.add(ls);
        ls.setVisible(true);
    }//GEN-LAST:event_btnHistoryActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JDesktopPane Desktop1;
    private javax.swing.JButton btnACC;
    public static javax.swing.JButton btnCate;
    private javax.swing.JButton btnFolow;
    private javax.swing.JButton btnHistory;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnRank;
    private javax.swing.JButton btnSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList<String> jList1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JMenuItem menuChuong;
    private javax.swing.JMenuItem menuDMK;
    private javax.swing.JMenuItem menuDX;
    private javax.swing.JMenuItem menuTG;
    private javax.swing.JMenuItem menuTL;
    private javax.swing.JMenuItem menuTruyen;
    public static javax.swing.JMenuBar mnu;
    // End of variables declaration//GEN-END:variables
    private void fill() {
        DefaultListModel model = (DefaultListModel) jList1.getModel();
        model.clear();
        List<Truyen> list = tRDAO.selectAll();
        if(list == null){
            return;
        }
        for (Truyen tr :list) {
            model.addElement(new Truyen(tr.getName(), new ImageIcon("E:\\DuAn1\\appDocTruyen\\src\\com\\imgStory\\" + tr.getHinh())));
        }
        jList1.setCellRenderer(new Renderer());
        jList1.setModel(model);
    }
}
