/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ui;

import com.ui.mainForm;
import com.dao.chuongDAO;
import com.dao.truyenDAO;
import com.models.Chuong;
import com.models.Truyen;
import java.io.FileOutputStream;
import java.util.Base64;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import org.icepdf.ri.common.ComponentKeyBinding;
import org.icepdf.ri.common.SwingController;
import org.icepdf.ri.common.SwingViewBuilder;

/**
 *
 * @author admin
 */
public class PDFform extends javax.swing.JInternalFrame {

    /**
     * Creates new form PDFform
     */
    chuongDAO cDAO = new chuongDAO();
    truyenDAO tRDAO = new truyenDAO();

    public PDFform() {
        initComponents();
        loadPDF();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnPre = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        cboChuong = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();

        setClosable(true);
        setMaximizable(true);

        btnPre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/image/previous.png"))); // NOI18N

        btnNext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/image/next.png"))); // NOI18N

        cboChuong.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Chương 1" }));
        cboChuong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboChuongActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1229, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(495, 495, 495)
                .addComponent(btnPre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cboChuong, 0, 168, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnNext)
                .addGap(462, 462, 462))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnNext, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnPre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cboChuong, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 714, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cboChuongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboChuongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboChuongActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnPre;
    private javax.swing.JComboBox<String> cboChuong;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
    private void loadPDF() {
        String name = mainForm.name;
        Truyen tr = tRDAO.selectByName( name);
        List<Chuong> list = cDAO.selectByTID(tr.getId());
        Chuong cg = list.get(0) ;
        String base64 = cg.getFilePDF();
        String pdf = "src//com//chapter//"+cg.getTenChuong()+".pdf";
        try (FileOutputStream imgOutFile = new FileOutputStream(pdf)){
            //convert from String to  Image
            byte [] imgByteArray = Base64.getDecoder().decode(base64);
            imgOutFile.write(imgByteArray);
        } catch (Exception e) {
            System.out.println("loi");
        }
        openpdf(pdf);
    }

    void openpdf(String file) {

        try {
            SwingController control = new SwingController();
            SwingViewBuilder factry = new SwingViewBuilder(control);
            JPanel veiwerCompntpnl = factry.buildViewerPanel();
            ComponentKeyBinding.install(control, veiwerCompntpnl);
            control.getDocumentViewController().setAnnotationCallback(
                    new org.icepdf.ri.common.MyAnnotationCallback(
                            control.getDocumentViewController()));
            control.openDocument(file);
            jScrollPane1.setViewportView(veiwerCompntpnl);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Cannot Load Pdf");
        }
    }
    private void loadCBO(){
        
    }
}
