/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ui;

import com.dao.HISDAO;
import com.dao.chiTietDAO;
import com.dao.chuongDAO;
import com.dao.tacGiaDAO;
import com.dao.theLoaiDAO;
import com.dao.truyenDAO;
import com.models.Chuong;
import com.models.History;
import com.models.Truyen;
import com.models.chiTietTruyen;
import com.models.tacGia;
import com.models.theLoai;
import com.ui.mainForm;
import static com.ui.mainForm.Desktop1;
import com.utils.MsgBox;

import com.utils.XImage;
import java.awt.Dimension;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JDesktopPane;
import static com.ui.PDFform.flag2;
/**
 *
 * @author admin
 */
public class ThongTinTruyen extends javax.swing.JInternalFrame {

    /**
     * Creates new form ThongTinTruyen
     */
    theLoaiDAO tLDAO = new theLoaiDAO();
    truyenDAO dao = new truyenDAO();
    tacGiaDAO tGDAO = new tacGiaDAO();
    chuongDAO cDAO = new chuongDAO();
    chiTietDAO cTDAO = new chiTietDAO();
    HISDAO hDAO = new HISDAO();
    List<History> listHS = new ArrayList<>();
    DefaultListModel model = new DefaultListModel();
    String name = mainForm.name;
    public static String nameChuong = "";
    public static boolean flag1;
    public static int index;
    public ThongTinTruyen() {
        initComponents();
        init();

        add();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblIMG = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtName = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtStatus = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listCg = new javax.swing.JList<>();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        txaGT = new javax.swing.JTextArea();
        jScrollPane1 = new javax.swing.JScrollPane();
        listTl = new javax.swing.JList<>();
        txtTacGia = new javax.swing.JLabel();
        btnRead = new javax.swing.JButton();
        btnFollow = new javax.swing.JButton();

        setClosable(true);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Thông tin truyện");

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblIMG.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(lblIMG, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 176, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addComponent(lblIMG, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel3.setText("Tác giả:");

        txtName.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtName.setText("Tên truyện");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel5.setText("Trạng thái");

        txtStatus.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtStatus.setText("Đang cập nhật");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel7.setText("Thể loại");

        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        listCg.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        listCg.setModel(new DefaultListModel());
        listCg.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        listCg.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        listCg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listCgMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(listCg);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 688, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 374, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Danh sách chương", jPanel3);

        txaGT.setEditable(false);
        txaGT.setColumns(20);
        txaGT.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        txaGT.setRows(5);
        jScrollPane4.setViewportView(txaGT);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 688, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 374, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Giới thiệu", jPanel4);

        listTl.setModel(new DefaultListModel());
        jScrollPane1.setViewportView(listTl);

        txtTacGia.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtTacGia.setText("Tác giả");

        btnRead.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/image/read.png"))); // NOI18N
        btnRead.setText("Đọc truyện");
        btnRead.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReadActionPerformed(evt);
            }
        });

        btnFollow.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/image/heart.png"))); // NOI18N
        btnFollow.setText("Theo dõi");
        btnFollow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFollowActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(54, 54, 54)
                                .addComponent(txtName))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(70, 70, 70)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel3))
                                        .addGap(53, 53, 53)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtTacGia)
                                            .addComponent(txtStatus)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addGap(69, 69, 69)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnFollow, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(btnRead, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(82, 82, 82))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtName)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(txtTacGia))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(txtStatus))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(212, 212, 212)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnFollow, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnRead, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnReadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReadActionPerformed
        // TODO add your handling code here:
        flag2 = false;
        Truyen tr = dao.selectByName(name);
        List<Chuong> list = cDAO.selectByTID(tr.getId());
        if (list == null) {
            MsgBox.alert(this, "Truyện đang được cập nhật");
            return;
        }
        flag1 = true;
        PDFform pdf = new PDFform();
        Desktop1.add(pdf);
        pdf.setVisible(true);
        if (check()) {
            return;
        }
        addHis();
    }//GEN-LAST:event_btnReadActionPerformed

    private void listCgMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listCgMouseClicked
        // TODO add your handling code here:       
        flag1 = false;
        flag2 = false;
        nameChuong = String.valueOf(listCg.getSelectedValue());
        index = listCg.getSelectedIndex();
        System.out.println(index);
        System.out.println(nameChuong);
        PDFform pdf = new PDFform();
        Desktop1.add(pdf);
        pdf.setVisible(true);
        if (check()) {
            return;
        }
        addHis();

    }//GEN-LAST:event_listCgMouseClicked

    private void btnFollowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFollowActionPerformed
        
    }//GEN-LAST:event_btnFollowActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFollow;
    private javax.swing.JButton btnRead;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblIMG;
    private javax.swing.JList<String> listCg;
    private javax.swing.JList<String> listTl;
    private javax.swing.JTextArea txaGT;
    private javax.swing.JLabel txtName;
    private javax.swing.JLabel txtStatus;
    private javax.swing.JLabel txtTacGia;
    // End of variables declaration//GEN-END:variables
    private void init() {
        JDesktopPane Desktop1 = mainForm.Desktop1;
        Dimension size1 = Desktop1.getSize();
        Dimension size = this.getSize();
        this.setLocation((size1.width - size.width) / 2, (size1.height - size.height) / 2);
        model = (DefaultListModel) listCg.getModel();
        txaGT.setColumns(20);
        txaGT.setLineWrap(true);
        txaGT.setRows(5);
        txaGT.setWrapStyleWord(true);
        jScrollPane4.setViewportView(txaGT);
        fillToList();
    }

    private void add() {

        Truyen tr = dao.selectByName(name);
        if (tr == null) {
            return;
        }
        txtName.setText(tr.getName());
        if (tr.getTrangThai() == false) {
            txtStatus.setText("Hoàn thành");
        }
        tacGia tg = tGDAO.selectByID(tr.getTacGia());
        txtTacGia.setText(tg.getName());
        txaGT.setText(tr.getGioiThieu());

        List<Chuong> list = cDAO.selectByTID(tr.getId());
        if (list == null) {
            model.addElement(null);
        } else {
            for (Chuong c : list) {
                model.addElement(c.getTenChuong());
            }
            listCg.setModel(model);
        }
        if (tr.getHinh() != null) {
            lblIMG.setIcon(new ImageIcon("E:\\DuAn1\\appDocTruyen\\src\\com\\imgStory\\" + tr.getHinh()));
        }
    }

    private void fillToList() {
        Truyen tr = dao.selectByName(name);
        if (tr == null) {
            return;
        }
        List<chiTietTruyen> list = cTDAO.selectListByID(tr.getId());
        if (list == null) {
            return;
        }
        DefaultListModel model = (DefaultListModel) listTl.getModel();
        model.clear();

        for (chiTietTruyen cT : list) {

            try {
                theLoai tL = tLDAO.selectByID(cT.getTheLoai());
                model.addElement(tL.getTenTL());
            } catch (SQLException ex) {
                Logger.getLogger(ThongTinTruyen.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

    }

    private boolean check() {
        try {
            listHS = hDAO.selectAll();
            Truyen tr = dao.selectByName(name);
            for (History hs : listHS) {
                if (tr.getId() == hs.getTruyen_id()) {
                    return true;
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(ThongTinTruyen.class.getName()).log(Level.SEVERE, null, ex);
        }
        return false;
    }

    private void addHis() {
        Truyen tr = dao.selectByName(name);
        History hs = new History();
        hs.setTruyen_id(tr.getId());
        hDAO.insert(hs);
    }

    private void readChuong() {

    }
}
