/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ui;

import com.dao.chiTietDAO;
import com.dao.theLoaiDAO;
import com.dao.truyenDAO;
import com.models.Truyen;
import com.models.chiTietTruyen;
import com.models.theLoai;
import static com.ui.mainForm.flag;
import com.utils.Renderer;
import java.awt.Event;
import java.awt.event.ActionListener;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;

/**
 *
 * @author admin
 */
public class timKiem extends javax.swing.JInternalFrame {

    /**
     * Creates new form timKiem
     */
    theLoaiDAO tDAO = new theLoaiDAO();
    chiTietDAO cTDAO = new chiTietDAO();
    truyenDAO trDA0 = new truyenDAO();
    public timKiem() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtname = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listTruyen = new javax.swing.JList<>();

        setClosable(true);

        txtname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtnameKeyReleased(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Tên truyện");

        listTruyen.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        listTruyen.setModel(new DefaultListModel());
        listTruyen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listTruyenMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(listTruyen);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(54, 54, 54)
                .addComponent(txtname, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(240, 240, 240))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 845, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtname, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 542, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtnameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnameKeyReleased
        // TODO add your handling code here:
        fill();
    }//GEN-LAST:event_txtnameKeyReleased

    private void listTruyenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listTruyenMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_listTruyenMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> listTruyen;
    private javax.swing.JTextField txtname;
    // End of variables declaration//GEN-END:variables
    private List<Truyen> role(){      
        String name = txtname.getText();
        List<Truyen> listTR = new ArrayList<>();
        
        if(flag == true){          
            try {
                theLoai tl = tDAO.getIDByName(name);
                if(tl == null){
                    return null;
                }
                List<chiTietTruyen> list = cTDAO.selectListByIDTL(tl.getId());
                if(list == null){
                    return null;
                }
                for(chiTietTruyen ct : list){
                    Truyen tr = trDA0.selectByID(ct.getTruyen());
                    listTR.add(tr);
                }
                
            } catch (SQLException ex) {
                Logger.getLogger(timKiem.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else{
            Truyen tr = trDA0.selectByName(name);
            if(tr == null){
                return null;
            }
            listTR.add(tr);
        }
        return listTR;
    }
    private void fill() {
        DefaultListModel model = (DefaultListModel) listTruyen.getModel();
        model.clear();
        List<Truyen> list = role();
        if(list == null){
            return;
        }
        for (Truyen tr :list) {
            model.addElement(new Truyen(tr.getName(), new ImageIcon("E:\\DuAn1\\appDocTruyen\\src\\com\\imgStory\\" + tr.getHinh())));
        }
        listTruyen.setCellRenderer(new Renderer());
        listTruyen.setModel(model);
    }
}
